# Generated by Django 2.0 on 2021-02-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=6)),
                ('open_pos_yur_long', models.IntegerField()),
                ('open_pos_yur_short', models.IntegerField()),
                ('open_pos_fiz_long', models.IntegerField()),
                ('open_pos_fiz_short', models.IntegerField()),
                ('open_pos_all', models.IntegerField()),
                ('number_persons_yur_long', models.IntegerField()),
                ('number_persons_yur_short', models.IntegerField()),
                ('number_persons_fiz_long', models.IntegerField()),
                ('number_persons_fiz_short', models.IntegerField()),
                ('number_persons_all', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='data',
            unique_together={('datetime', 'code')},
        ),
    ]
